# =========================== Basic Settings ===========================
# machine info
num_gpus_per_job: 1  # number of gpus each job need
num_cpus_per_job: 4  # number of gpus each job need
num_hosts_per_job: 1
memory_per_job: 32  # number of gpus each job need
gpu_type: 'nvidia-tesla-v100'

# parameters
name: esc50_gated_conv_v100  # any name
model_restore: ''  # logs/places2_gated_conv
dataset: 'esc50'  # 'tmnist', 'dtd', 'places2', 'celeba', 'imagenet', 'cityscapes'
random_crop: False  # Set to false when dataset is 'celebahq', meaning only resize the images to img_shapes, instead of crop img_shapes from a larger raw image. This is useful when you train on images with different resolutions like places2. In these cases, please set random_crop to true.
val: True  # true if you want to view validation results in tensorboard
log_dir: logs/cur/full_model_esc50_15seg_time_mask_only_with_brush_transpose

gan: 'sngan'
gan_loss_alpha: 1.
gan_with_mask: True
discounted_mask: True
random_seed: False
padding: 'SAME'
fuse: True

# training
train_spe: 4000
max_iters: 100000000
viz_max_out: 6
val_psteps: 2000
NUM_GPUS: 2
GPU_ID: [0, 1]
log_progress: True
mask_initialize: False
with_ir_mask: True
viz_coarse: True
viz_audio: True
viz_flow_sep: True

# audio
sr: 44100

# data
data_flist:
  # https://github.com/jiahuiyu/progressive_growing_of_gans_tf
  celebahq: [
    'data/celeba_hq/train_shuffled.flist',
    'data/celeba_hq/validation_static_view.flist'
  ]
  # http://mmlab.ie.cuhk.edu.hk/projects/celeba.html, please to use random_crop: True
  celeba: [
    'data/celeba/train_shuffled.flist',
    'data/celeba/validation_static_view.flist'
  ]
  # http://places2.csail.mit.edu/, please download the high-resolution dataset and use random_crop: True
  places2: [
    'data/places2/train_shuffled.flist',
    'data/places2/validation_static_view.flist'
  ]
  # http://www.image-net.org/, please use random_crop: True
  imagenet: [
    'data/imagenet/train_shuffled.flist',
    'data/imagenet/validation_static_view.flist'
  ]
  # audio to spectrogram https://github.com/karolpiczak/ESC-50
  esc50: [
    'data/esc50/spec_15seg/train_shuffled.flist',
    'data/esc50/spec_15seg/validation_static_view.flist'                 
  ]
  # AudioSet from Google, parts of. # 111k
  audioset: [
    'data/audioset/spec_15seg/train_shuffled.flist',
    'data/audioset/spec_15seg/validation_static_view.flist'
  ]



filetype: 'npy'             # default: image, npy
transpose: True
static_view_size: 30
img_shapes: [256, 256, 1]
height: 96
width: 255                   # max of mask width
max_delta_height: 64         # max decrease of mask side
max_delta_width: 0
batch_size: 16
vertical_margin: 97
horizontal_margin: 0       # width + 1

# loss
ae_loss: True
l1_loss: True
l1_loss_alpha: 1.

# to tune
guided: False
edge_threshold: 0.6
